### ISSUE TITLE
Does your octo.nvim + 1password integration works for you?

### ISSUE THREAD

**Issue by Demianeen** [mrjones2014/dotfiles#123]
I just found your issue and quickly looked up at how you integrated octo.nvim and 1password. But it gives an error that gh is expected to be a table, not a function

![CleanShot 2024-05-27 at 10 23 15@2x](https://github.com/mrjones2014/dotfiles/assets/51330172/233d4247-51b9-4647-b8d7-fe2c7ed6457f)

I have updated to the latest Octo version so far. I tried on stable (v0.10.0) and nightly (v0.11.0-dev-49+g10601ac5f)

Does Octo and 1Password integration still work for you?

P.S. You have a nice config. I already have stolen hammerspoon config)

**Comment by mrjones2014** [comment]
Yeah looks like a bug was introduced in `octo.nvim`. It's supposed to accept a function or a table. I'll make a PR.

**Comment by mrjones2014** [comment]
https://github.com/pwntester/octo.nvim/pull/550

Should be fixed if/when this PR merges.

**Comment by mrjones2014** [comment]
> hammerspoon config

Funny you should mention that as I actually am hoping to drop my last macOS machine soon :sweat_smile:  hoping to swap my work computer for a Linux machine.

**Comment by mrjones2014** [comment]
Also what is that bar you have at the bottom below wezterm?

**Comment by Demianeen** [comment]
> > hammerspoon config
> 
> Funny you should mention that as I actually am hoping to drop my last macOS machine soon 😅 hoping to swap my work computer for a Linux machine.

Why have you decided to drop macos support?

**Comment by Demianeen** [comment]
> Also what is that bar you have at the bottom below wezterm?

sketchybar, written in lua
the borders are JankyBorders)

you can take a look at my [dotfiles](https://github.com/Demianeen/dotfiles) if you want the code

**Comment by mrjones2014** [comment]
> Why have you decided to drop macos support?

I just prefer to use NixOS these days, also macOS has a lot of weird display bugs.

sketchybar looks cool!

**Comment by Demianeen** [comment]
> I just prefer to use NixOS these days, also macOS has a lot of weird display bugs.

Is the nix/NixOS config hard to maintain? Because I am ready to invest time into that stuff but I wonder how hard it is to maintain it

**Comment by mrjones2014** [comment]
I'd say Nix the language can be a bit difficult to learn, the syntax is pretty unique lol but once you get the hang of it, it becomes pretty simple to add onto it, and I've never had a more stable Linux system than NixOS. I use it both on my gaming/dev PC as well as my home server now, both configs are all in this dotfiles repo if you wanna take a look.

**Comment by Demianeen** [comment]
Okay, thanks, I will take a look for nix for macos)
