### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by tsyroid** [mrjones2014/dotfiles#16]
I want to introduce what I consider to be a 'feature request' although I acknowledge up front it might ultimately induce some 'breaking changes' into your dotfiles (which in my world, is sacred ground).

Here's what a propose (and I'm totally open to how it happens; and I'm totally open to the mechanisms; meaning I'll do my part to contribute anything and everything you deem necessary):

I'd like to see your `config/nvim` split out from your `dotfiles`.

This way, I could clone and monitor your `nvim/config` files as a separate entity. Currently, I cannot, and I have to jump through a bunch of hoops to do so.

This could easily be done as a submodule, of course, but I'm more interested in your thoughts (in general) and any other option you might have in mind.

**Comment by mrjones2014** [comment]
This will make keeping everything up to date more complicated for me. I don't want to have to keep two separate repos up to date. The Neovim config also depends on a bunch of LSP servers and other linting/formatting tools being installed, which are listed in `.config/fish/functions/check-globals.fish`.

You can just do a git sparse checkout:

```sh
git init mrjones2014-nvim
cd mrjones2014-nvim
git remote add -f origin git@github.com:mrjones2014/dotfiles.git
git config core.sparseCheckout true
echo ".config/nvim/" >> .git/info/sparse-checkout
git pull origin master
```

Then create a symlink. You could wrap this up in a simple bash function.

**Comment by tsyroid** [comment]
Awesome. All good. Understand fully your desire for simple, and giving me the above helps hugely in my understanding of how to leverage git in ways I don't yet understand.
You can close this at your leisure.
