### ISSUE TITLE
Thanks for the Fish config....

### ISSUE THREAD

**Issue by olimorris** [mrjones2014/dotfiles#18]
🤗  @mrjones2014 !

Absolutely loved borrowing your Fish config over the last week. The jump has been well worth it and the terminal feels like light speed!

**Comment by mrjones2014** [comment]
Hey, nice, glad you like it! There’s some neat goodies in there. 

One of my favorite bits if you haven’t tried it out is [this function](https://github.com/mrjones2014/dotfiles/blob/master/.config/fish/functions/conf.fish). Basically, set up paths in `~/.config/config-paths.yml` and then run `conf something` to open the config for `something` in Neovim, or run `conf` by itself to put the options into fzf.

**Comment by olimorris** [comment]
Oh that is an absolute beauty!
