### ISSUE TITLE
Redundant `expr` lua escaping with `nest`

### ISSUE THREAD

**Issue by LionC** [mrjones2014/dotfiles#4]
https://github.com/mrjones2014/dotfiles/blob/e6aace2c67a030fb0b3900fff035081c0982fece/.config/nvim/lua/modules/keymaps.lua#L4

This function is not needed when using `nest` - it already handles the returned strings from lua `expr` functions correctly :-)

Another small hint: normal mode is default in `nest`, so you do not need to explicitly set `mode = 'n'` if you did not explicitly set another mode in it's parent (unless you want to do so for stylistic reasons of course).

**Comment by mrjones2014** [comment]
oh awesome thanks for the tip! I wasn't sure.

**Comment by mrjones2014** [comment]
actually turned out the issue was compe so I switched to cmp.
