### ISSUE TITLE
Use vim.filetype.match to get the lsp config?

### ISSUE THREAD

**Issue by towry** [mrjones2014/dotfiles#55]
https://github.com/mrjones2014/dotfiles/blob/981b6b029c1a59a51e99de38072d2c0f0323a97b/nvim/lua/my/configure/lspconfig.lua#L117C7-L117C7

Just wondering if `vim.filetype.match` can be used here to make it easier to get lsp config instead of pattern matching.

FYI, the above code can cause lsp server to setup multiple times and result in same server started multiple instance on one buffer.

**Comment by mrjones2014** [comment]
> Just wondering if vim.filetype.match can be used here to make it easier to get lsp config instead of pattern matching.

it probably can but the patterns are also used for the autocmd that lazy loads the config, so I need the pattern anyway. 

> FYI, the above code can cause lsp server to setup multiple times and result in same server started multiple instance on one buffer.

No it can’t, the autocmd has `once = true`
