### ISSUE TITLE
Arkenfox integration

### ISSUE THREAD

**Issue by theRoboxx** [mrjones2014/dotfiles#77]
I'm also looking for a way to include the arkenfox.nix to my nix config.
Unfortunately, the [documention](https://github.com/dwarfmaster/arkenfox-nixos) isn't clear enough for me.
I'm going to open another issue up there and ask for more instructions.

**Comment by theRoboxx** [comment]
Try this one https://github.com/dwarfmaster/arkenfox-nixos/issues/42#issuecomment-1870485750

**Comment by mrjones2014** [comment]
I think I've got this mostly working, but it doesn't work on macOS so I've got it commented out for now. I plan to switch fully to NixOS this summer, so once I don't have a mac anymore, I can just remove the mac targets and merge it.

**Comment by mrjones2014** [comment]
Been using Arkenfox on NixOS for a month or so now.
